**Câu 1** Thêm thư viện numpy và gán thành **np**

In [1]:
# Lập trình tại đây
import numpy as np







**Câu 2** Định nghĩa Vector bằng numpy

Có nhiều cách ký hiệu vectors khác nhau, hình ảnh bên dưới miêu tả một số cách ký hiệu thường gặp:

<img src="https://github.com/thanhhff/AIVN-Machine-Learning/blob/master/Week%201/images/Linear-Algebra/la_0.png?raw=1" style="width:30%;height:30%;"> 

Hãy định nghĩa vector  $\textbf{v}$ với giá trị phía trên:

In [2]:
# Lập trình tại đây
v = np.array([1, 2, 3])








Cho 2 vector $\textbf{x}$ và $\textbf{y}$

![img](https://latex.codecogs.com/gif.latex?%5Cdpi%7B300%7D%20%24%5Ctextbf%7B%1Dx%7D%24%20%3D%20%5Cbegin%7Bbmatrix%7D%201%5C%5C%202%5C%5C%203%20%5Cend%7Bbmatrix%7D%20%24%5Ctextbf%7B%1Dy%7D%24%20%3D%20%5Cbegin%7Bbmatrix%7D%202%5C%5C%203%5C%5C%204%20%5Cend%7Bbmatrix%7D)




**Câu 3** Tính $\textbf{x} + \textbf{y}$

In [3]:
# Lập trình tại đây
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
x + y 









array([3, 5, 7])

**Câu 4** Tính $\textbf{x} - \textbf{y}$

In [4]:
# Lập trình tại đây
x - y









array([-1, -1, -1])

**Câu 5** Tính $\textbf{x} / \textbf{y}$

In [5]:
# Lập trình tại đây
x / y









array([0.5       , 0.66666667, 0.75      ])

**Câu 6** Tính 2$\textbf{x} - 3\textbf{y}$

In [6]:
# Lập trình tại đây
2*x - 3*y









array([-4, -5, -6])

**Câu 7** Tính tích vô hướng 2 vector $\textbf{x}\cdot\textbf{y}$



In [7]:
# Lập trình tại đây
x.dot(y)








20

**Câu 8** Tính tích Hadamard product 2 vector $\textbf{x}\bigodot\textbf{y}$


Công thức nhân Hadamard:

<img src="https://github.com/thanhhff/AIVN-Machine-Learning/blob/master/Week%201/images/Linear-Algebra/la_5.png?raw=1" style="width:30%;height:30%;"> 


In [8]:
# Lập trình tại đây
x * y







array([ 2,  6, 12])

**Câu 9**: Lập trình tính giá trị biểu thức sau

$4||\textbf{x}||^2_2 - 2||\textbf{y}||_1 + 1$



In [9]:
# Lập trình tại đây
from numpy.linalg import norm
4*(norm(x, 2) ** 2) - 2*norm(y, 1) + 1










39.0

Cho 2 ma trận

A = \begin{bmatrix}
1 & - 1 & 2 \\ 
2 & 3 & 4 \\
4 & 1 & 5
\end{bmatrix}

B = \begin{bmatrix}
2 & -1 \\
3 & -4 \\
4 & -5 \\
\end{bmatrix}

**Câu 10:** Lập trình tính $A \cdot B$

In [10]:
# Lập trình tại đây
A = np.array([
             [1, -1, 2],
             [2, 3, 4],
             [4, 1, 5]
             ])

B = np.array([
             [2, -1],
             [3, -4],
             [4, -5]
             ])

A.dot(B)




array([[  7,  -7],
       [ 29, -34],
       [ 31, -33]])

**Câu 11** Lập trình tính $A^TB$

[Cách chuyển vị](https://numpy.org/doc/stable/reference/generated/numpy.matrix.transpose.html) trong numpy

In [11]:
# Lập trình tại đây
np.transpose(A).dot(B)









array([[ 24, -29],
       [ 11, -16],
       [ 36, -43]])

**Câu 12** Lập trình in ra chiều của 2 ma trận $A$ và $B$

In [12]:
# Lập trình tại đây
print(A.shape)
B.shape







(3, 3)


(3, 2)

**Câu 13** Lập trình tính $A^2$

Gợi ý: $A^2$ = $A \bigodot A$

In [13]:
# Lập trình tại đây
A**2






array([[ 1,  1,  4],
       [ 4,  9, 16],
       [16,  1, 25]], dtype=int32)

**Câu 14** Lập trình tính $A^TAA(BB^T)$

In [14]:
# Lập trình tại đây
(np.transpose(A).dot(A.dot(A))).dot(B.dot(np.transpose(B)))







array([[ 4119,  9786, 12567],
       [ 2626,  6269,  8048],
       [ 6285, 14940, 19185]])

**Câu 15** Khám phá việc thay đổi chiều của ma trận 






X là ma trận có chiều (5, 4) với tất cả những giá trị bằng 1

In [15]:
X = np.ones((5, 4))

Chuyển chiều ma trận này từ (5, 4) thành ma trận (10, 2)

Tham khảo [cách dùng](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) và thực hành ở dưới:



In [16]:
# Lập trình tại đây
X = X.reshape(10, 2)
X








array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])