Import:

In [1]:
import pandas as pd
import random
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import accuracy_score

Đọc dữ liệu:

In [2]:
df = pd.read_csv("ex2data1.csv")
X = df[['x1', 'x2']].values#.reshape(-1, 2)
Y = df['y'].values#.reshape(-1)

### Manual:

In [3]:
k = 5 # thiết lập giá trị K
print(X[0:5])

[[34.62365962 78.02469282]
 [30.28671077 43.89499752]
 [35.84740877 72.90219803]
 [60.18259939 86.3085521 ]
 [79.03273605 75.34437644]]


Xáo trộn:

In [4]:
nSamples = X.shape[0]
for i in range(nSamples):
    j = random.randint(0, nSamples - 1)
    t = X[i]
    X[i] = X[j]
    X[j] = t
    u = Y[i]
    Y[i] = Y[j]
    Y[j] = u

In [5]:
foldSize = round(nSamples/k) # Chia phần tử cho K fold
foldSize # kích thước 1 fold

20

In [6]:
for step in range(k): # Lặp từng Fold, đầu tiên step = 0
    print("fold {}/{}-----------------------".format(step + 1, k))
    
    # Tại bước step (0 <= step < k), xác định tập huấn luyện và tập test:
    start = step*foldSize
    if step == k-1:
        stop = nSamples-1
    else:
        stop = (step+1)*foldSize - 1

    print("test set in [{},{}]".format(start, stop))

    X_test = X[start:stop]
    y_test = Y[start:stop]

    if step==0:
        X_train = X[stop:nSamples-1]
        y_train = Y[stop:nSamples-1]
    elif step==(k-1):
        X_train = X[0:start-1]
        y_train = Y[0:start-1]
    else:
        X_train = np.concatenate((X[0:start-1], X[stop:nSamples-1]))
        y_train = np.concatenate((Y[0:start-1], Y[stop:nSamples-1]))

fold 1/5-----------------------
test set in [0,19]
fold 2/5-----------------------
test set in [20,39]
fold 3/5-----------------------
test set in [40,59]
fold 4/5-----------------------
test set in [60,79]
fold 5/5-----------------------
test set in [80,99]


Thực hiện học:

In [7]:
regr = LogisticRegression()
regr.fit(X_train, y_train)

LogisticRegression()

Đánh giá kết quả tại mỗi bước:

In [8]:
y_pred = regr.predict(X_test)
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy", accuracy_score(y_test, y_pred))

[[ 2  3]
 [ 3 11]]
accuracy 0.6842105263157895


#### ================================================================

### Buil-in:

In [9]:
from sklearn.model_selection import KFold

Tạo đối tượng KFold:

In [10]:
kf = KFold(n_splits = 5)

Thiết lập vòng lặp từng fold:

In [11]:
for train_index, test_index in kf.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    regr = LogisticRegression()
    regr.fit(X_train, y_train)

    y_pred = regr.predict(X_test)
    cm = metrics.confusion_matrix(y_test, y_pred)
    print(cm)
    print("accuracy", accuracy_score(y_test, y_pred))

[[ 3  4]
 [ 1 12]]
accuracy 0.75
[[3 7]
 [4 6]]
accuracy 0.45
[[ 4  6]
 [ 0 10]]
accuracy 0.7
[[ 1  6]
 [ 3 10]]
accuracy 0.55
[[ 2  4]
 [ 3 11]]
accuracy 0.65
