In [1]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split, KFold
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import accuracy_score
import cv2
import matplotlib.pyplot as plt
import pandas as pd
import random
import numpy as np

In [2]:
df = pd.read_csv("ex2data1.csv")
X = df[['x1', 'x2']].values.reshape(-1, 2)
Y = df['y'].values.reshape(-1)

### Manual:

In [3]:
k = 5 # chia thành 5 bộ
nSamples = X.shape[0]
print(X[0], X[1], X[2],X[3])

[34.62365962 78.02469282] [30.28671077 43.89499752] [35.84740877 72.90219803] [60.18259939 86.3085521 ]


In [4]:
for i in range(nSamples):
    j = random.randint(0, nSamples-1)
    t = X[i]
    X[i] = X[j]
    X[j] = t
    u = Y[i]
    Y[i] = Y[j]
    Y[j] = u
print(X[0], X[1], X[2], X[3])

[70.66150955 92.92713789] [40.23689374 71.16774802] [60.18259939 86.3085521 ] [51.54772027 46.85629026]


In [5]:
foldSize = round(nSamples/k)
for step in range(k):
    print("fold {}/{}-----------------------".format(step+1, k))

    start = step*foldSize
    if step==k-1:
        stop = nSamples-1
    else:
        stop = (step+1)*foldSize - 1

    print("test set in [{},{}]".format(start, stop))

    X_test = X[start:stop]
    y_test = Y[start:stop]

    if step==0:
        X_train = X[stop:nSamples-1]
        y_train = Y[stop:nSamples-1]
    elif step==(k-1):
        X_train = X[0:start-1]
        y_train = Y[0:start-1]
    else:
        X_train = np.concatenate((X[0:start-1], X[stop:nSamples-1]))
        y_train = np.concatenate((Y[0:start-1], Y[stop:nSamples-1]))

fold 1/5-----------------------
test set in [0,19]
fold 2/5-----------------------
test set in [20,39]
fold 3/5-----------------------
test set in [40,59]
fold 4/5-----------------------
test set in [60,79]
fold 5/5-----------------------
test set in [80,99]


In [6]:
regr = LogisticRegression()
regr.fit(X_train, y_train)

y_pred = regr.predict(X_test)
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy", accuracy_score(y_test, y_pred))

[[ 4  4]
 [ 0 11]]
accuracy 0.7894736842105263


**=======================================================================**

### Buil-in:

In [7]:
kf = KFold(n_splits = 5)

In [8]:
for train_index, test_index in kf.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    regr = LogisticRegression()
    regr.fit(X_train, y_train)

    y_pred = regr.predict(X_test)
    cm = metrics.confusion_matrix(y_test, y_pred)
    print(cm)
    print("accuracy", accuracy_score(y_test, y_pred))

[[6 2]
 [3 9]]
accuracy 0.75
[[5 1]
 [6 8]]
accuracy 0.65
[[5 4]
 [2 9]]
accuracy 0.7
[[5 4]
 [6 5]]
accuracy 0.5
[[ 4  4]
 [ 0 12]]
accuracy 0.8
