In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
import csv

**Hàm sinh ngẫu nhiên tập dữ liệu:**

In [2]:
# w ~ vector a1*x1 + a2*x2 + … +  an*xn
# b ~ a0
# n là chính nó
def randomPointsAroundHyperlane( w, b, n ):
    X = []
    Y = []
    for i in range( n ):
        x = np.random.uniform( -1.0, 1.0, size = w.shape )
        y = np.dot( x, w ) + b
        
        X.append( x + np.random.uniform( -0.1, 0.1, size = x.shape ) )
        Y.append( y + np.random.uniform( -0.1, 0.1 ) )
    return np.array( X ), np.array( Y )               

In [3]:
X = []
Y = []
w = np.random.uniform( -1.0, 1.0, size=(5) )
b = random.uniform( -1, 1 )
for i in range( 5 ):
    x = np.random.uniform( -1.0, 1.0, size = w.shape ) # len(x) = len(w)
    y = np.dot( x, w ) + b
        
    X.append( x + np.random.uniform( -0.1, 0.1, size = x.shape ) )
    Y.append( y + np.random.uniform( -0.1, 0.1 ) )
#return np.array( X ), np.array( Y )

### w, b, random:

In [4]:
w

array([ 0.03432983,  0.47207459, -0.37913693,  0.53006817, -0.28865257])

In [5]:
np.random.uniform( -1.0, 1.0, size=(5) )

array([-0.87940218, -0.81156039,  0.35291678, -0.73848375,  0.70574113])

In [6]:
np.random.uniform( -1.0, 1.0, size=5 )

array([ 0.93790034, -0.38554505,  0.06014434,  0.53187297,  0.75966422])

In [7]:
b

-0.7282691882378132

### x, y, np.dot:

In [8]:
x

array([ 0.62371176,  0.61649333,  0.31478752, -0.22845781,  0.83228431])

In [9]:
y

-0.8965132304659896

In [10]:
np.dot(w, x)

-0.16824404222817646

In [11]:
y = w*x + b

In [12]:
y

array([-0.70685727, -0.43723835, -0.84761676, -0.8493674 , -0.9685102 ])

In [13]:
print( len( x ) )
print( len( w ) )

5
5


### Vì sao bài này không cần :
```np.array( X ).reshape( ( -1, x.shape[0] ) )```

In [14]:
X

[array([ 0.96726869,  0.77022536,  0.92658646, -0.27569232,  0.70700188]),
 array([ 0.85567924, -0.19508866, -0.78563006, -0.42563096,  0.77932777]),
 array([-0.9082825 , -0.89142886, -0.31691295, -0.02221358, -0.61354491]),
 array([ 0.07174275,  0.59361297,  0.84853871,  0.62747928, -0.59278773]),
 array([ 0.57537187,  0.52948936,  0.40296636, -0.1778066 ,  0.7441175 ])]

In [15]:
X_arr = np.array( X )
X_arr

array([[ 0.96726869,  0.77022536,  0.92658646, -0.27569232,  0.70700188],
       [ 0.85567924, -0.19508866, -0.78563006, -0.42563096,  0.77932777],
       [-0.9082825 , -0.89142886, -0.31691295, -0.02221358, -0.61354491],
       [ 0.07174275,  0.59361297,  0.84853871,  0.62747928, -0.59278773],
       [ 0.57537187,  0.52948936,  0.40296636, -0.1778066 ,  0.7441175 ]])

In [16]:
X[0]

array([ 0.96726869,  0.77022536,  0.92658646, -0.27569232,  0.70700188])

In [17]:
X_arr[0]

array([ 0.96726869,  0.77022536,  0.92658646, -0.27569232,  0.70700188])