In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
import cv2
import pandas as pd
import csv

### C1: Sử dụng csv: 

In [2]:
X = []
Y = []
with open('ex2data1.csv', mode='r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        X.append([float(row['x1']), float(row['x2'])])
        Y.append(float(row['y']))
type(X), X, type(X), Y

(list,
 [[34.62365962451697, 78.0246928153624],
  [30.28671076822607, 43.89499752400101],
  [35.84740876993872, 72.90219802708364],
  [60.18259938620976, 86.30855209546826],
  [79.0327360507101, 75.3443764369103],
  [45.08327747668339, 56.3163717815305],
  [61.10666453684766, 96.51142588489624],
  [75.02474556738889, 46.55401354116538],
  [76.09878670226257, 87.42056971926803],
  [84.43281996120035, 43.53339331072109],
  [95.86155507093572, 38.22527805795094],
  [75.01365838958247, 30.60326323428011],
  [82.30705337399482, 76.48196330235604],
  [69.36458875970939, 97.71869196188608],
  [39.53833914367223, 76.03681085115882],
  [53.9710521485623, 89.20735013750205],
  [69.07014406283025, 52.74046973016765],
  [67.94685547711617, 46.67857410673128],
  [70.66150955499435, 92.92713789364831],
  [76.97878372747498, 47.57596364975532],
  [67.37202754570876, 42.83843832029179],
  [89.6767757507208, 65.79936592745237],
  [50.534788289883, 48.85581152764205],
  [34.21206097786789, 44.2095285986

(list,
 [[34.62365962451697, 78.0246928153624],
  [30.28671076822607, 43.89499752400101],
  [35.84740876993872, 72.90219802708364],
  [60.18259938620976, 86.30855209546826],
  [79.0327360507101, 75.3443764369103],
  [45.08327747668339, 56.3163717815305],
  [61.10666453684766, 96.51142588489624],
  [75.02474556738889, 46.55401354116538],
  [76.09878670226257, 87.42056971926803],
  [84.43281996120035, 43.53339331072109],
  [95.86155507093572, 38.22527805795094],
  [75.01365838958247, 30.60326323428011],
  [82.30705337399482, 76.48196330235604],
  [69.36458875970939, 97.71869196188608],
  [39.53833914367223, 76.03681085115882],
  [53.9710521485623, 89.20735013750205],
  [69.07014406283025, 52.74046973016765],
  [67.94685547711617, 46.67857410673128],
  [70.66150955499435, 92.92713789364831],
  [76.97878372747498, 47.57596364975532],
  [67.37202754570876, 42.83843832029179],
  [89.6767757507208, 65.79936592745237],
  [50.534788289883, 48.85581152764205],
  [34.21206097786789, 44.2095285986

In [3]:
X = np.array(X)
Y = np.array(Y)
#print(type(X)), print(type(Y)) 
type(X), X, type(X), Y

(numpy.ndarray,
 array([[34.62365962, 78.02469282],
        [30.28671077, 43.89499752],
        [35.84740877, 72.90219803],
        [60.18259939, 86.3085521 ],
        [79.03273605, 75.34437644],
        [45.08327748, 56.31637178],
        [61.10666454, 96.51142588],
        [75.02474557, 46.55401354],
        [76.0987867 , 87.42056972],
        [84.43281996, 43.53339331],
        [95.86155507, 38.22527806],
        [75.01365839, 30.60326323],
        [82.30705337, 76.4819633 ],
        [69.36458876, 97.71869196],
        [39.53833914, 76.03681085],
        [53.97105215, 89.20735014],
        [69.07014406, 52.74046973],
        [67.94685548, 46.67857411],
        [70.66150955, 92.92713789],
        [76.97878373, 47.57596365],
        [67.37202755, 42.83843832],
        [89.67677575, 65.79936593],
        [50.53478829, 48.85581153],
        [34.21206098, 44.2095286 ],
        [77.92409145, 68.97235999],
        [62.27101367, 69.95445795],
        [80.19018075, 44.82162893],
        [93.

(numpy.ndarray,
 array([[34.62365962, 78.02469282],
        [30.28671077, 43.89499752],
        [35.84740877, 72.90219803],
        [60.18259939, 86.3085521 ],
        [79.03273605, 75.34437644],
        [45.08327748, 56.31637178],
        [61.10666454, 96.51142588],
        [75.02474557, 46.55401354],
        [76.0987867 , 87.42056972],
        [84.43281996, 43.53339331],
        [95.86155507, 38.22527806],
        [75.01365839, 30.60326323],
        [82.30705337, 76.4819633 ],
        [69.36458876, 97.71869196],
        [39.53833914, 76.03681085],
        [53.97105215, 89.20735014],
        [69.07014406, 52.74046973],
        [67.94685548, 46.67857411],
        [70.66150955, 92.92713789],
        [76.97878373, 47.57596365],
        [67.37202755, 42.83843832],
        [89.67677575, 65.79936593],
        [50.53478829, 48.85581153],
        [34.21206098, 44.2095286 ],
        [77.92409145, 68.97235999],
        [62.27101367, 69.95445795],
        [80.19018075, 44.82162893],
        [93.

### C2: Sử dụng pandas: *pd.read_csv()* & *values.reshape()*

In [4]:
df = pd.read_csv('ex2data1.csv')
type(df), df

(pandas.core.frame.DataFrame,
            x1         x2  y
 0   34.623660  78.024693  0
 1   30.286711  43.894998  0
 2   35.847409  72.902198  0
 3   60.182599  86.308552  1
 4   79.032736  75.344376  1
 ..        ...        ... ..
 95  83.489163  48.380286  1
 96  42.261701  87.103851  1
 97  99.315009  68.775409  1
 98  55.340018  64.931938  1
 99  74.775893  89.529813  1
 
 [100 rows x 3 columns])

(pandas.core.frame.DataFrame,
            x1         x2  y
 0   34.623660  78.024693  0
 1   30.286711  43.894998  0
 2   35.847409  72.902198  0
 3   60.182599  86.308552  1
 4   79.032736  75.344376  1
 ..        ...        ... ..
 95  83.489163  48.380286  1
 96  42.261701  87.103851  1
 97  99.315009  68.775409  1
 98  55.340018  64.931938  1
 99  74.775893  89.529813  1
 
 [100 rows x 3 columns])

In [5]:
X = df[['x1','x2']].values.reshape(-1, 2)
Y = df['y'].values.reshape(-1)
type(X), X, type(X), Y

(numpy.ndarray,
 array([[34.62365962, 78.02469282],
        [30.28671077, 43.89499752],
        [35.84740877, 72.90219803],
        [60.18259939, 86.3085521 ],
        [79.03273605, 75.34437644],
        [45.08327748, 56.31637178],
        [61.10666454, 96.51142588],
        [75.02474557, 46.55401354],
        [76.0987867 , 87.42056972],
        [84.43281996, 43.53339331],
        [95.86155507, 38.22527806],
        [75.01365839, 30.60326323],
        [82.30705337, 76.4819633 ],
        [69.36458876, 97.71869196],
        [39.53833914, 76.03681085],
        [53.97105215, 89.20735014],
        [69.07014406, 52.74046973],
        [67.94685548, 46.67857411],
        [70.66150955, 92.92713789],
        [76.97878373, 47.57596365],
        [67.37202755, 42.83843832],
        [89.67677575, 65.79936593],
        [50.53478829, 48.85581153],
        [34.21206098, 44.2095286 ],
        [77.92409145, 68.97235999],
        [62.27101367, 69.95445795],
        [80.19018075, 44.82162893],
        [93.

(numpy.ndarray,
 array([[34.62365962, 78.02469282],
        [30.28671077, 43.89499752],
        [35.84740877, 72.90219803],
        [60.18259939, 86.3085521 ],
        [79.03273605, 75.34437644],
        [45.08327748, 56.31637178],
        [61.10666454, 96.51142588],
        [75.02474557, 46.55401354],
        [76.0987867 , 87.42056972],
        [84.43281996, 43.53339331],
        [95.86155507, 38.22527806],
        [75.01365839, 30.60326323],
        [82.30705337, 76.4819633 ],
        [69.36458876, 97.71869196],
        [39.53833914, 76.03681085],
        [53.97105215, 89.20735014],
        [69.07014406, 52.74046973],
        [67.94685548, 46.67857411],
        [70.66150955, 92.92713789],
        [76.97878373, 47.57596365],
        [67.37202755, 42.83843832],
        [89.67677575, 65.79936593],
        [50.53478829, 48.85581153],
        [34.21206098, 44.2095286 ],
        [77.92409145, 68.97235999],
        [62.27101367, 69.95445795],
        [80.19018075, 44.82162893],
        [93.

### C3: Sử dụng pandas: *pd.read_csv().values*

In [6]:
data = pd.read_csv('ex2data1.csv').values
X = data[:, 0:2].reshape(-1, 2)
Y = data[:, 2].reshape(-1)

In [7]:
type(X), X, type(X), Y

(numpy.ndarray,
 array([[34.62365962, 78.02469282],
        [30.28671077, 43.89499752],
        [35.84740877, 72.90219803],
        [60.18259939, 86.3085521 ],
        [79.03273605, 75.34437644],
        [45.08327748, 56.31637178],
        [61.10666454, 96.51142588],
        [75.02474557, 46.55401354],
        [76.0987867 , 87.42056972],
        [84.43281996, 43.53339331],
        [95.86155507, 38.22527806],
        [75.01365839, 30.60326323],
        [82.30705337, 76.4819633 ],
        [69.36458876, 97.71869196],
        [39.53833914, 76.03681085],
        [53.97105215, 89.20735014],
        [69.07014406, 52.74046973],
        [67.94685548, 46.67857411],
        [70.66150955, 92.92713789],
        [76.97878373, 47.57596365],
        [67.37202755, 42.83843832],
        [89.67677575, 65.79936593],
        [50.53478829, 48.85581153],
        [34.21206098, 44.2095286 ],
        [77.92409145, 68.97235999],
        [62.27101367, 69.95445795],
        [80.19018075, 44.82162893],
        [93.

(numpy.ndarray,
 array([[34.62365962, 78.02469282],
        [30.28671077, 43.89499752],
        [35.84740877, 72.90219803],
        [60.18259939, 86.3085521 ],
        [79.03273605, 75.34437644],
        [45.08327748, 56.31637178],
        [61.10666454, 96.51142588],
        [75.02474557, 46.55401354],
        [76.0987867 , 87.42056972],
        [84.43281996, 43.53339331],
        [95.86155507, 38.22527806],
        [75.01365839, 30.60326323],
        [82.30705337, 76.4819633 ],
        [69.36458876, 97.71869196],
        [39.53833914, 76.03681085],
        [53.97105215, 89.20735014],
        [69.07014406, 52.74046973],
        [67.94685548, 46.67857411],
        [70.66150955, 92.92713789],
        [76.97878373, 47.57596365],
        [67.37202755, 42.83843832],
        [89.67677575, 65.79936593],
        [50.53478829, 48.85581153],
        [34.21206098, 44.2095286 ],
        [77.92409145, 68.97235999],
        [62.27101367, 69.95445795],
        [80.19018075, 44.82162893],
        [93.