In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
import csv

In [2]:
X = []
Y = []

In [3]:
with open('forestfires.csv', mode = 'r') as csv_file:
    for i in csv_file:
        print(i)
    print(type(i)) # <class 'str'>

X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area

7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0,0

7,4,oct,tue,90.6,35.4,669.1,6.7,18,33,0.9,0,0

7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0,0

8,6,mar,fri,91.7,33.3,77.5,9,8.3,97,4,0.2,0

8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0,0

8,6,aug,sun,92.3,85.3,488,14.7,22.2,29,5.4,0,0

8,6,aug,mon,92.3,88.9,495.6,8.5,24.1,27,3.1,0,0

8,6,aug,mon,91.5,145.4,608.2,10.7,8,86,2.2,0,0

8,6,sep,tue,91,129.5,692.6,7,13.1,63,5.4,0,0

7,5,sep,sat,92.5,88,698.6,7.1,22.8,40,4,0,0

7,5,sep,sat,92.5,88,698.6,7.1,17.8,51,7.2,0,0

7,5,sep,sat,92.8,73.2,713,22.6,19.3,38,4,0,0

6,5,aug,fri,63.5,70.8,665.3,0.8,17,72,6.7,0,0

6,5,sep,mon,90.9,126.5,686.5,7,21.3,42,2.2,0,0

6,5,sep,wed,92.9,133.3,699.6,9.2,26.4,21,4.5,0,0

6,5,sep,fri,93.3,141.2,713.9,13.9,22.9,44,5.4,0,0

5,5,mar,sat,91.7,35.8,80.8,7.8,15.1,27,5.4,0,0

8,5,oct,mon,84.9,32.8,664.2,3,16.7,47,4.9,0,0

6,4,mar,wed,89.2,27.9,70.8,6.3,15.9,35,4,0,0

6,4,apr,sat,86.3,27.4,97.1,5.1,9.3,44,4.5,0

In [4]:
with open('forestfires.csv', mode = 'r') as csv_file:
    csv_reader = csv.DictReader(csv_file)   
    for k in csv_reader:
        print(k)
    print(type(k)) # <class 'dict'>

{'X': '7', 'Y': '5', 'month': 'mar', 'day': 'fri', 'FFMC': '86.2', 'DMC': '26.2', 'DC': '94.3', 'ISI': '5.1', 'temp': '8.2', 'RH': '51', 'wind': '6.7', 'rain': '0', 'area': '0'}
{'X': '7', 'Y': '4', 'month': 'oct', 'day': 'tue', 'FFMC': '90.6', 'DMC': '35.4', 'DC': '669.1', 'ISI': '6.7', 'temp': '18', 'RH': '33', 'wind': '0.9', 'rain': '0', 'area': '0'}
{'X': '7', 'Y': '4', 'month': 'oct', 'day': 'sat', 'FFMC': '90.6', 'DMC': '43.7', 'DC': '686.9', 'ISI': '6.7', 'temp': '14.6', 'RH': '33', 'wind': '1.3', 'rain': '0', 'area': '0'}
{'X': '8', 'Y': '6', 'month': 'mar', 'day': 'fri', 'FFMC': '91.7', 'DMC': '33.3', 'DC': '77.5', 'ISI': '9', 'temp': '8.3', 'RH': '97', 'wind': '4', 'rain': '0.2', 'area': '0'}
{'X': '8', 'Y': '6', 'month': 'mar', 'day': 'sun', 'FFMC': '89.3', 'DMC': '51.3', 'DC': '102.2', 'ISI': '9.6', 'temp': '11.4', 'RH': '99', 'wind': '1.8', 'rain': '0', 'area': '0'}
{'X': '8', 'Y': '6', 'month': 'aug', 'day': 'sun', 'FFMC': '92.3', 'DMC': '85.3', 'DC': '488', 'ISI': '14.7'

In [5]:
with open('forestfires.csv', mode='r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        Y.append(float(row['area']))
        X.append( [float( row["X"] ),float( row["Y"] ), 
                   float( row["FFMC"] ),float( row["DMC"] ),float( row["DC"] ),float( row["ISI"] ), 
                   float( row["temp"] ),float( row["RH"] ),float( row["wind"] ),float( row["rain"] )] )        

In [6]:
X = np.array(X)
X

array([[ 7. ,  5. , 86.2, ..., 51. ,  6.7,  0. ],
       [ 7. ,  4. , 90.6, ..., 33. ,  0.9,  0. ],
       [ 7. ,  4. , 90.6, ..., 33. ,  1.3,  0. ],
       ...,
       [ 7. ,  4. , 81.6, ..., 70. ,  6.7,  0. ],
       [ 1. ,  4. , 94.4, ..., 42. ,  4. ,  0. ],
       [ 6. ,  3. , 79.5, ..., 31. ,  4.5,  0. ]])

In [7]:
X[2]

array([  7. ,   4. ,  90.6,  43.7, 686.9,   6.7,  14.6,  33. ,   1.3,
         0. ])

In [8]:
Y = np.array(X)
Y

array([[ 7. ,  5. , 86.2, ..., 51. ,  6.7,  0. ],
       [ 7. ,  4. , 90.6, ..., 33. ,  0.9,  0. ],
       [ 7. ,  4. , 90.6, ..., 33. ,  1.3,  0. ],
       ...,
       [ 7. ,  4. , 81.6, ..., 70. ,  6.7,  0. ],
       [ 1. ,  4. , 94.4, ..., 42. ,  4. ,  0. ],
       [ 6. ,  3. , 79.5, ..., 31. ,  4.5,  0. ]])

In [9]:
Y[0]

array([ 7. ,  5. , 86.2, 26.2, 94.3,  5.1,  8.2, 51. ,  6.7,  0. ])