In [1]:
# Complete!

# Bài tập lập trình: Python trong Machine Learning / Deep Learning

Trong bài tập lập trình này, các bạn sẽ ôn lại các chức năng cơ bản về toán học và thư viện Numpy. 

**Một số chú ý:**
- Trong bài tập này bạn sẽ sử dụng Python 3.
- Cố gắng không sử dụng các vòng lặp (for, while). 
- Không chỉnh sửa các tên hàm. 
- Sau khi bạn viết Code của mình xong, hãy chạy dòng Code đó để xem kết quả bên dưới. 

**Sau bài tập này bạn sẽ:**
- Có thể sử dụng các hàm trong thư viện `Numpy` và các phép tính numpy matrix/vector.
- Phân biệt được sự khác nhau giữa thư viện `math` và thư viện `numpy`.
- Kỹ thuật "Broadcasting".
- Thực hiện tính toán trên các Vector.

Hãy bắt đầu nào!

## Hướng dẫn làm bài ##

Các bạn sẽ bắt đầu Code trong phần `### START CODE HERE ###` và `### END CODE HERE ###`. Các bạn hãy nhớ đừng sửa bất kỳ tên hàm nào ngoài phần Code này. 

Sau khi viết xong Code của bạn, bạn hãy ấn "SHIFT"+"ENTER" để thực hiện chạy lệnh của Cell đó. Sau đó kiểm tra với kết quả có sẵn bên dưới để xem đã thực hiện đúng hay sai, nếu sai hãy thử lại !

Trong phần Code: các bạn hãy cố gắng thực hiện ít dòng Code nhất theo chỉ định "(≈ X lines of code)". Mặc dù đây không phải là hạn chế về số dòng Code của bạn, nhưng hãy tối ưu sao cho ít nhất có thể.

<font color='blue'>
**Một số điều bạn nên nhớ**:
    
- Chạy `Cells` bằng SHIFT + ENTER (hoặc nhấn "Run Cell")
- Chỉ sử dụng Python 3 để code
- Không chỉnh sửa bất cứ thứ gì bên ngoài hàm 

## 1) Sử dụng Numpy xây dựng 1 số hàm cơ bản ##

- Trong bài tập này, bạn sẽ thực hiện 1 vài hàm từ thư viện numpy như: np.exp, np.log, np.reshape,... 

(Truy cập vào trang chủ [numpy](www.numpy.org) để xem chi tiết hơn.)



### 1.1 - sigmoid function, np.exp() ###
Trước khi sử dụng np.exp(), bạn sẽ sử dụng hàm math.exp() để thực hiện hàm `Sigmoid`. Bạn sẽ thấy lý do tại sao chúng ta sử dụng np.exp() thay cho math.exp().

**Bài tập 1.1**: Thực hiện xây dựng hàm `Sigmoid` với số thực x. Sử dụng `math.exp()` cho phần hàm này.

**Nhắc lại**:
$sigmoid(x) = \frac{1}{1+e^{-x}}$ : là hàm phi tuyến được sử dụng rộng rãi trong Machine Learning.

![](https://imgur.com/MyypY7K.png)
<!-- <img src="https://imgur.com/MyypY7K.png" style="width:20%;height:50%;"> -->

In [2]:
# GRADED FUNCTION: basic_sigmoid

import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar 

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + math.exp(-x))
    ### END CODE HERE ###
    
    return s

In [3]:
basic_sigmoid(10)

0.9999546021312976

**Đầu ra kỳ vọng**: 
```python
0.9999546021312976
```

Trong thực tế, chúng ta không sử dụng thư viện `math` trong Machine Learning / Deep Learning (ML/DL) bởi vì đầu vào của hàm này là số thực.
Trong ML/DL đầu vào của chúng ta thường là matrices và vectors. Đó chính là lý do `numpy` hữu ích hơn.

In [5]:
### Lý do mà chúng ta sử dung 'numpy' thay cho 'math' trong ML/DL ###
x = [1, 2, 3]

# Khi chạy Cell này: các bạn sẽ thấy lỗi vì x là vector.
basic_sigmoid(x) 

TypeError: ignored

Nếu ta có $ x = (x_1, x_2, ..., x_n)$ là 1 vector hàng thì $np.exp(x)$ sẽ thực hiện tính toán trên từng phần tử của x. Vì vậy, chúng ta sẽ có kết quả như sau: $np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})$

In [6]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


Hơn nữa, nếu x là 1 vector, thì khi thực hiện $s = x + 3$ hay $s = \frac{1}{x}$ sẽ cho đầu ra cùng kích thước với x.

In [7]:
# example of vector operation
x = np.array([1, 2, 3])
print('x + 3:', x + 3)
print('1 / x:', 1/x)

x + 3: [4 5 6]
1 / x: [1.         0.5        0.33333333]


Các hàm trong thư viện Numpy tương đối là nhiều và rất hữu ích, nếu bạn cần sử dụng hàm nào hãy lên trang tài liệu chính thức của Nympy [Xem thêm tại đây](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.exp.html). 

**Bài tập 1.2**: Thực hiện hàm `Sigmoid` sử dụng `numpy`.

**Hướng dẫn**: bây giờ, x có thể là 1 vô hướng, 1 vector hay 1 matrix. Cấu trúc của dạng này là các (vectors, matrices...) được gọi là các numpy array. 
$$ \text{Với } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1} $$

In [8]:
# GRADED FUNCTION: sigmoid

import numpy as np
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + np.exp(-x))
    ### END CODE HERE ###
    
    return s

In [9]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

**Đầu ra kỳ vọng**: 

```python
array([0.73105858, 0.88079708, 0.95257413])
```


### 1.2 - Đạo hàm của hàm Sigmoid

**Bài tập 2**: Thực hiện hàm sigmoid_grad() để tính đạo hàm của hàm Sigmoid với đầu vào là x. Công thức toán học: $$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$

**Hướng dẫn**:
Bạn sẽ thực hiện 2 bước trong phần này:
1. Thực hiện gọi hàm sigmoid với đầu vào là x (Hàm Sigmoid sử dụng `numpy` mà các bạn đã viết ở trên).
2. Tính $\sigma'(x) = s(1-s)$

In [10]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    s = sigmoid(x)
    ds = s*(1 - s)
    ### END CODE HERE ###
    
    return ds

In [11]:
x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


**Đầu ra kỳ vọng**: 
```python
sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]
```



### 1.3 - Reshaping arrays ###

Hai hàm được sử dụng phổ biến trong ML/DL là [np.shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) và [np.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html). 
- X.shape: đưa ra số chiều của matrix/vector X.
- X.reshape(...): định hình lại X sang một chiều khác.

**Câu hỏi phụ**: Các bạn hãy phân biệt sự khác nhau giữa `Transpose` và `Reshape`.

**Ans:** Phân biệt `Transpose` và `Reshape`:

+) `Reshape` nhận một ma trận với hình dạng đầu vào và định dạng lại ma trận đó sao cho số lượng hàng và cột thay đổi; nhưng bố cục, thứ tự dữ liệu thì không đổi. Hiểu đơn giản thì `Reshape` làm thẳng ma trận rồi cắt ra thành các hàng theo hình dạng mới. 

+) `Transpose` thì thay đổi bố cục, thứ tự dữ liệu ban đầu.

In [12]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print('Matrix A:\n', A)
print('Transpose: \n', A.T)
print('Reshape: \n', A.reshape(2, 3))

Matrix A:
 [[1 2]
 [3 4]
 [5 6]]
Transpose: 
 [[1 3 5]
 [2 4 6]]
Reshape: 
 [[1 2 3]
 [4 5 6]]


Trong Computer Science, xét ảnh RGB được đại diện bởi 1 matrix 3 chiều có shape $(length, height, depth = 3)$

Tuy nhiên, khi bạn thực hiện đưa ảnh vào 1 thuật toán bạn cần chuyển nó thành vector có shape $(length*height*3, 1)$. Nói cách khác là bạn **"unroll"**, hay reshape 3D matrix thành 1D vector.

![alt text](https://imgur.com/6ySOTB1.png)
<!-- <img src="images/image2vector_kiank.png" style="width:500px;height:300;"> -->

**Bài tập 3**: Thực hiện hàm `image2vector()` với đầu vào có shape(length, height, 3) và đầu ra là vector có (length\*height\*3, 1). 

Ví dụ, bạn có 1 array v có shape(a, b, c) -> chúng ta mong muốn đầu ra là 1 vector có shape (a*b, c).

``` python
v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c
```

In [13]:
# GRADED FUNCTION: image2vector
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    v = image.reshape((image.shape[0]*image.shape[1]*image.shape[2], 1))
    # hoặc: v = image.reshape((-1, 1)) 
    ### END CODE HERE ###
    
    return v

In [14]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


**Đầu ra kỳ vọng**: 
```python
image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
```


### 1.4 - Normalizing rows

Một kỹ thuật phổ biến khác trong ML / DL là chuẩn hoá dữ liệu. Sau khi chuẩn hoá, chúng ta sẽ có hiệu suất tốt hơn vì Gradient Descent hội tụ nhanh hơn. Ở phần này, chúng ta sẽ chuẩn hoá x thành $ \frac{x}{\| x\|} $ (Chia mỗi vector của x cho Norm tương ứng của nó). 

Ví dụ, với $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{3}$$ và $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{4} $$thì ta có        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{5}$$ 

Lưu ý: bạn có thể nhân, chia ma trận có kích thước khác nhau và nó vẫn hoạt động tốt. Đây là kỹ thuật "broadcasting" mà sẽ được tìm hiểu trong phần 1.5. Hoặc bạn có thể xem thêm tại [đây](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm?fbclid=IwAR0mN3dYIvickJiDwOU7ayjBk5JKNo9wbZWGsyDWMQVA-eQ-Y__3Q4dD-kw)

**Bài tập 4**: Thực hiện hàm normalizeRows() để chuẩn hoá theo hàng của matrix. Sau khi thực hiện hàm này với đầu vào là matrix x bạn sẽ có đầu ra là vector độ dài (có nghĩa là length của vector bằng 1).

In [15]:
# GRADED FUNCTION: normalizeRows

def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    ### START CODE HERE ### (≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    # ord = 2 có nghĩa là trong phần này chúng ta đang input matrix 2D.
    x_norm = np.linalg.norm(x, ord = 2, axis = 1, keepdims = True)
    print("x_norm shape: ", x_norm.shape)
    
    # Divide x by its norm.
    x = x / x_norm
    print("x shape: ", x.shape)

    ### END CODE HERE ###

    return x

In [16]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

x_norm shape:  (2, 1)
x shape:  (2, 3)
normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


**Đầu ra kỳ vọng**: 
```python
normalizeRows(x) = [[0.         0.6        0.8       ]
                    [0.13736056 0.82416338 0.54944226]]
```

**Chú ý**:

Trong normalizeRows(), bạn hãy thử bỏ comment `print` và in ra shapes của x_norm và x. Và chạy lại phần này, bạn sẽ thấy chúng khác nhau về số chiều (shape). Mặc dù nó khác nhau số chiều, nhưng vẫn có thể thực hiện tính toán được bình thường, đây gọi là kỹ thuật "broadcasting".

### 1.5 - Broadcasting và hàm Softmax ####


Một khái niệm quan trọng tỏng numpy là "broadcasting". Nó hữu ích cho việc tính toán giữa các arrays với số chiều khác nhau. Để tìm hiểu thêm, bạn có thể đọc chi tiết tại [broadcasting documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

Với kỹ thuật broadcasting, chúng ta có thể dùng phép toán (a+b). Lúc này, vector b sẽ nhân bản ra để có cùng shape với a, và phép toán được thực hiện theo các thông thường.

![alt text](https://imgur.com/DVKmFQW.png)
<!-- <img src="images/broadcasting.png" style="width:800px;height:400;"> -->

**Bài tập 5**: Thực hiện hàm `softmax` sử dụng `numpy`. Hàm `softmax` giúp chúng ta phân loại nhiều classes (multi-class). Bạn sẽ được học về softmax trong các tuần tới. 

**Hướng dẫn**:
- $ \text{Với } x \in \mathbb{R}^{1\times n} \text{,     } softmax(x) = softmax(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n 
\end{bmatrix}) = \begin{bmatrix}
     \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}} 
\end{bmatrix} $ 

- $\text{Matrix } x \in \mathbb{R}^{m \times n}$, $x_{ij}$ ánh xạ tới từng phần từ ở hàng thứ $i^{th}$ cột  $j^{th}$ trong $x$, do đó chúng ta có:

$ softmax(x) = softmax\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
\end{bmatrix} = \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} = \begin{pmatrix}
    softmax\text{(hàng thứ nhất của x)}  \\
    softmax\text{(hàng thứ hai của x)} \\
    ...  \\
    softmax\text{(hàng cuối của x)} \\
\end{pmatrix} $

In [17]:
# GRADED FUNCTION: softmax

def softmax(x):
    """Thực hiện hàm softmax cho mỗi hàng của input x.

    Code của bạn sẽ thực hiện trên mỗi hàng của vector.
    
    Ma trận x có kích thước shape(m ,n).

    Argument:
    x -- A numpy matrix of shape (m,n)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (m,n)
    """
    
    ### START CODE HERE ### (≈ 3 lines of code)
    # Sử dụng exp() element-wise (tính toán trên từng phần tử) cho x. Dùng: np.exp(...).
    x_exp = np.exp(x)
    print('x_exp - shape:',x_exp.shape)

    # Tạo vector x_sum với tổng theo hàng của x_exp. Use: np.sum(..., axis = 1, keepdims = True).
    # Đầu vào của chúng ta là matrix 2 chiều nên:
    # axis = 0 tương đương với tính tổng theo chiều dọc (cột)
    # axis = 1 tương đương với tính tổng theo chiều ngang (hàng)
    # keepdims = True -> giữ số chiều giống đầu vào.  
    
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    print('x_sum - shape', x_sum.shape)
    
    # Thực hiện hàm softmax(x) bằng phép chia x_exp cho x_sum. Bạn nên sử dụng kỹ thuật 'broadcasting'.
    s = x_exp / x_sum

    ### END CODE HERE ###
    
    return s

In [18]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

y = np.array([[9], 
              [5]])
print("y shape: ", y.shape)
print('x / y: ', x / y)

x_exp - shape: (2, 5)
x_sum - shape (2, 1)
softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
y shape:  (2, 1)
x / y:  [[1.         0.22222222 0.55555556 0.         0.        ]
 [1.4        1.         0.         0.         0.        ]]


**Đầu ra kỳ vọng**:
```python
x_exp - shape: (2, 5)
x_sum - shape (2, 1)
softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04 1.21052389e-04]
              [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04 8.01252314e-04]]
(2, 1)
x / y:  [[1.         0.22222222 0.55555556 0.         0.        ]
         [1.4        1.         0.         0.         0.        ]]
```


**Chú ý**:

- Nếu bạn in ra số chiều của x_exp, x_sum. Bạn sẽ thấy x_sum có shape(2, 1) trong khi đó x_exp và s có shape (2, 5). **x_exp/x_sum** hoạt động được do 'broadcasting'.


Chúc mừng bạn đã hoàn thành phần Code bên trên về python numpy và kỹ thuật 'broadcasting'. Nó là các hàm hữu ích trong ML / DL. 

<font color='blue'>
**Tổng kết một số điều bạn nên nhớ:**
    
- np.exp(x) hoạt động trên từng phần tử của np.array x và thực hiện hàm e mũ trên từng phần tử trong x.

- Hàm sigmoid và đạo hàm của nó.

- Chuyển hình ảnh 3D sang vector (image2vector), rất hữu ích trong deep learning.

- Thực hiện chuyển đổi số chiều với np.reshape.

- Kỹ thuật 'broadcasting' rất hiệu quả trong tính toán.

## 2) Vectorization

Trong ML / DL, bạn sẽ sử dụng với những bộ dữ liệu lớn. Vì thế mà chúng ta cần phải sử dụng thuật toán tối ưu để tính toán, tránh lãng phí thời gian. Bạn nên vector hoá (vectorization) sẽ giúp tính toán hiệu quả hơn. 

Một vài ví dụ bên dưới, bạn sẽ thấy sự khác biệt giữa phép toán dot / outer / elementwise product sử dụng vectorization và vòng lặp for.

In [19]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.071772000000081ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

In [20]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.11098799999986753ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.1035480000002309ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0568210000000402ms
gdot = [19.68682584 20.20984359 29.99622137

Mặc dù với bộ dữ liệu nhỏ như ví dụ ở trên, bạn mới chỉ thấy thời gian chênh lệch không đáng kể. Nhưng với dữ liệu lớn, nó sẽ rất lãng phí thời gian chạy thuật toán của bạn.


**Lưu ý**: hàm `np.dot()` thực hiện phép nhân matrix-matrix hoặc matrix-vector. Nó khác với phép `np.multiply()` và `*`. ( `np.multiply()` và `*` có nghĩa là nhân từng phần tử hay còn gọi là phép `element-wise`).

### Thực hiện tính toán hàm Loss L1 và L2 



**Bài tập 6**: Thực hiện tính L1 loss với numpy. 

**Nhắc lại**:
- Hàm loss sẽ đánh giá hiệu suất của model. Nếu loss lớn điều đó có nghĩa là bạn giá trị dự đoán ($ \hat{y} $) sai khác lớn so với giá trị thực tế ($y$).
- L1 loss được định nghĩa như sau:
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^m|y^{(i)} - \hat{y}^{(i)}| \end{align*}\tag{6}$$

In [21]:
# GRADED FUNCTION: L1

def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.sum(abs(y - yhat))
    ### END CODE HERE ###
    
    return loss

In [22]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


**Đầu ra kỳ vọng**:

```python
L1 = 1.1
```


**Bài tập 7**: Thực hiện tính toán hàm L2 loss. 

Có một cách khác để thực hiện hàm L2 loss là bạn sử dụng np.dot(). 

Với: $x = [x_1, x_2, ..., x_n]$, thì `np.dot(x,x)` = $\sum_{j=0}^n x_j^{2}$. 

- Công thức hàm L2 Loss: $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^m(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [23]:
# GRADED FUNCTION: L2

def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    # Using function np.dot() useful.
    loss = np.dot(y - yhat, y - yhat)

    ### END CODE HERE ###
    
    return loss

In [24]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


**Đầu ra kỳ vọng**: 
```python
L2 = 0.43
```

Chúc mừng bạn đã hoàn thành bài tập này. Mong rằng nó sẽ giúp ích cho bạn !

<font color='blue'>
**Những điều bạn cần nhớ:**
    
- Vectorization rất quan trong trong Deep Learning. Nó giúp tính toán hiệu quả hơn. 

- Nhớ và phân biệt hàm loss: l1 và l2.

- Các hàm: np.sum, np.dot, np.multiply, np.maximun, ...

### Tài liệu tham khảo
[1] [Deep Learning - Coursera](https://coursera.org)