Tiêu chí chấm điểm:

*   Kết quả đúng với yêu cầu đề bài: 9 điểm
*   Lời giải ngắn gọn xúc tích: 1 điểm


In [ ]:
import tensorflow as tf

**Câu 1** Viết công thức đạo hàm của $f(x) = 3\sqrt{x}$ xuống dưới đây

In [ ]:
# Ví dụ công thức căn viết là x ** (1/2)

### Ans: 3/2 * x**(-1/2)

**Câu 2** Lập trình tính đạo hàm của $f(x)$ bên trên tại $x = 2.0$ bằng Gradient Tape. In giá trị này.

In [ ]:
# Lập trình tại đây
x = tf.constant(2.)
with tf.GradientTape() as g:
  g.watch(x)
  f = 3 * x**(1/2)

df_dx = g.gradient(f, x)
df_dx.numpy()

1.0606601

**Câu 3** Lập trình tính đạo hàm của hàm 
\
$f(x) =sin(x)^3cos(x)$ tại $x$ = $30^0$ bằng GradientTape.

Chú ý phải chuyển $x$ về radian thông qua công thức

$ \text{radiants} = \text{degrees} * \frac{\pi}{180}$ \

In giá trị đạo hàm này.

In [ ]:
import numpy as np

In [ ]:
# Lập trình tại đây
x = tf.constant(30. * np.pi / 180.)
with tf.GradientTape() as g:
  g.watch(x)
  f = (tf.math.sin(x))**3 * tf.math.cos(x)

df_dx = g.gradient(f, x)
df_dx.numpy()

0.49999994

**Câu 4** Lập trình tính đạo hàm của hàm 
\
$f(x) = \frac{\sqrt{x}}{\ln(x^2)}$ tại $x$ = $2.0$ bằng GradientTape. \

In giá trị này.


In [ ]:
# Lập trình tại đây
x = tf.constant(2.)
with tf.GradientTape() as g:
  g.watch(x)
  f = (x**(1/2)) / (tf.math.log(x**2))

df_dx = g.gradient(f, x)
df_dx.numpy()

-0.48084024

**Câu 5** Viết công thức Gradient của $\nabla{f}$ với $f(x, y) = 2x^2 + 6y - 30$ \
Gradient là tập hợp các đạo hàm riêng. \
$
\nabla{f} = \begin{bmatrix}
\frac{\partial{f(x, y)}}{\partial{x}} & \frac{\partial{f(x, y)}}{\partial{y}}
\end{bmatrix}
$


In [ ]:
# Ans [ 4x, 6 ]

**Câu 6** Lập trình tính đạo hàm riêng của $f(x)$: $\frac{\partial{f(x_1, x_2, x_3)}}{\partial{x_1}}$; $\frac{\partial{f(x_1, x_2, x_3)}}{\partial{x_2}}$; $\frac{\partial{f(x_1, x_2, x_3)}}{\partial{x_3}}$  
\
$f(x_1, x_2, x_3) = x_1^2x_2^3x_3, + 2x_1^2x_2$ tại $x_1$ = $2.0$; $x_2=4.0$ và  $x_3=-2.0$ bằng GradientTape. \
In 3 giá trị này.


In [ ]:
# Lập trình tại đây
x1 = tf.constant(2.)
x2 = tf.constant(4.)
x3 = tf.constant(-2.)

def cal(x):
  with tf.GradientTape() as g:
    g.watch(x)
    f1 = (x**2) * (x2**3) * x3 + 2 * (x**2) * x2
    f2 = (x1**2) * (x**3) * x3 + 2 * (x1**2) * x
    f3 = (x1**2) * (x2**3) * x + 2 * (x1**2) * x2
  if(x == x1):
    return g.gradient(f1, x)
  elif(x == x2): 
    return g.gradient(f2, x)
  else:
    return g.gradient(f3, x)

print(cal(x1).numpy())
print(cal(x2).numpy())
print(cal(x3).numpy())

-480.0
-376.0
256.0




**Câu 7** Lập trình tính đạo hàm riêng của của $f(\textbf{x},\textbf{y},\textbf{z})$ trên các vector $\textbf{x},\textbf{y},\textbf{z}$ \

$

\textbf{x} = \begin{bmatrix}
1\\ 
2\\ 
3
\end{bmatrix}

\textbf{y} = \begin{bmatrix}
4\\ 
-5\\ 
6
\end{bmatrix}

\textbf{z} = \begin{bmatrix}
-1\\ 
2\\ 
-4
\end{bmatrix}
\\

f(\textbf{x},\textbf{y},\textbf{z}) = (\textbf{x} \bigodot \textbf{y})\cdot \textbf{z}


$ \

In 3 giá trị đạo hàm riêng này.





In [ ]:
# Lập trình tại đây
x = tf.constant([[1.], [2.], [3.]], dtype = np.float32)
y = tf.constant([[4.], [-5.], [6.]], dtype = np.float32)
z = tf.constant([[-1.], [2.], [-4.]], dtype = np.float32)

def cal(t):
  with tf.GradientTape() as g:
    g.watch(t)
    f = tf.matmul(t*y, z, transpose_a=True)
    f1 = tf.matmul(x*t, z, transpose_a=True)
    f2 = tf.matmul(x*y, t, transpose_a=True)
  if((t == x).numpy()[0][0]):
    return g.gradient(f, t)
  elif((t == y).numpy()[0][0]):
    return g.gradient(f1, t)
  else:
    return g.gradient(f2, t)

print(cal(x))
print(cal(y))
print(cal(z))


tf.Tensor(
[[ -4.]
 [-10.]
 [-24.]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[ -1.]
 [  4.]
 [-12.]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[  4.]
 [-10.]
 [ 18.]], shape=(3, 1), dtype=float32)
